Loops(for) and conditional(if) operators have been replaced by vector…
neurodata/hyppo pull request #403
Opened 2023-08-20 16:26 UTC by quant12345

… operations.

#### Reference issue

#### Type of change

#### What does this implement/fix?

#### Additional information

After discussion here:[](https://github.com/neurodata/hyppo/issues/402)

I would like to improve the function code: prim from the class: FriedmanRafsky.

Since the function has a decorator: @jit(nopython=True, cache=True) using numba, the first start is warming up and lasts a long time. For a 100 x 100 array, it turned out 30 - 120 times slower than my version on the first run. True, subsequent launches are about 5 times faster than my version.

If you do not use numba, then the speedup is about 29 times with an array of 500 x 500. The speedup starts with an array size starting from 20 x 20.

2023-08-20 17:52 UTC, sampan501 commented
> Tests are down. I assume that the 'MST' function that calls 'prim' has a numba decorator. I tried locally without the decorator, the function worked without errors. I'll try to make the 'MST' function without loops so as not to use a decorator. If possible, show sample data: x, labels for the MST function.

Sounds good. After everything works, I'd like to see the wall times figure again as shown in #402

2023-08-21 16:36 UTC, quant12345 commented
I removed the numba decorators and its imports. I made a version of the 'MST' function without cycles, but did not add it to the commit. On the attached chart, the 'Rafsky_performance.py' script is running: the original is running without numba. Function MST_new(new_alg) is a variant without cycles,  MST_old_prim_new(new_alg_MSTold)  MST is calculated as before. Both options calculation the 'prim' function in a new way. It can be seen that the new version ' MST' begins to deteriorate sharply at the end.

The 'Rafsky_loop.py' script counts in cycles: displays the elapsed time of each algorithm. And the ratio of the original algorithm to one of the new algorithms (in this case, MST_new). As before, the first run in 70-130 slower on numba.

And the question is the list 'i_min' if it is empty, that is, there is no minimum, an error may occur, but this is in theory. I have run scripts dozens of times, this has never happened.
Can put a check on an empty list, but this will slightly reduce performance.?

I am attaching both scripts (Rafsky.tar.gz).
[Rafsky.tar.gz](https://github.com/neurodata/hyppo/files/12398657/Rafsky.tar.gz)
![Rafsky](https://github.com/neurodata/hyppo/assets/32775019/19bd926a-737d-4da8-844a-a9eb42e59c04)

2023-08-22 12:40 UTC, quant12345 commented
```
n 100
time_original         0:00:02.309068 
time_MST_old_prim_new 0:00:00.041586 
time_new              0:00:00.026029
difference in time original / new     88.71136040570133
difference in time original / MST_old 55.52512864906459
*******************************************************
n 205
time_original         0:00:02.260544 
time_MST_old_prim_new 0:00:00.197153 
time_new              0:00:00.101197
difference in time original / new     22.33805349960967
difference in time original / MST_old 11.46593762204988
*******************************************************
n 450
time_original         0:00:02.429262 
time_MST_old_prim_new 0:00:01.229136 
time_new              0:00:01.046668
difference in time original / new     2.320947998792358
difference in time original / MST_old 1.976398055219276new
```
Tried several times to run the loop with different options. With an array size of 100, the first run is 50-130 times faster than numba. In this case, the calculation in numba lasts two seconds. With an array of 205, the difference is already 10 - 30 times faster, with 450 the difference is 2-3 times.

Probably even at the first start numba starts to accelerate after a certain time. Because with an array size of 10, the first run on numba takes 2.30 seconds and the same elapsed time for an array of 100.

Attached is the 'newRafsky_loop.py' file. In it, at the first iteration, the ratio of time to the original algorithm is considered, and vice versa at all subsequent iterations. The data is printed out.

If you will merge, there is a question. INF = 9999999 used to initialize the first minimum (in my opinion, this is the largest number, in fact it is: np.inf ). 

Then **sample < minimum** is not needed. And instead of: 

`i_min = np.where((sample < minimum) & (sample == np.min(sample[np.nonzero(sample)])))`

just need:

`i_min = np.where(sample == np.min(sample[np.nonzero(sample)]))`

[newRafsky_loop.py.tar.gz](https://github.com/neurodata/hyppo/files/12408678/newRafsky_loop.py.tar.gz)

2023-09-05 08:15 UTC, quant12345 commented
> > Tests are down. I assume that the 'MST' function that calls 'prim' has a numba decorator. I tried locally without the decorator, the function worked without errors. I'll try to make the 'MST' function without loops so as not to use a decorator. If possible, show sample data: x, labels for the MST function.
> 
> Sounds good. After everything works, I'd like to see the wall times figure again as shown in #402

Will there be any reaction to the changes?

2023-09-08 12:49 UTC, quant12345 commented
@sampan501 
I left in i_min only finding the minimum, because I think that’s what happens in the original, since INF is simply the largest number. And tests and comparisons give identical arrays.
As a result, with numba the first launch is slower until about array size n - 450.

<details>

<summary>code tests</summary>

```
import numpy as np
import perfplot
from numba import jit

@jit(nopython=True, cache=True)  # pragma: no cover
def prim(weight_mat, labels):
    INF = 9999999
    V = len(labels)
    selected = np.zeros(len(labels))
    no_edge = 0
    selected[0] = True
    MST_connections = []

    while no_edge < V - 1:
        minimum = INF
        x = 0
        y = 0
        for i in range(V):
            if selected[i]:
                for j in range(V):
                    if (not selected[j]) and weight_mat[i][j]:
                        # not in selected and there is an edge
                        if minimum > weight_mat[i][j]:
                            minimum = weight_mat[i][j]
                            x = i
                            y = j
        MST_connections.append([x, y])
        selected[y] = True
        no_edge += 1

    return MST_connections


@jit(nopython=True, cache=True)
def MST(x, labels):  # pragma: no cover

    G = np.zeros((len(x[0]), len(x[0])))

    for i in range(len(x[0])):

        for j in range(i + 1, len(x[0])):
            weight = np.linalg.norm(x[:, i] - x[:, j])
            G[i][j] = weight
            G[j][i] = weight

    MST_connections = prim(G, labels)

    return MST_connections


def prim_new(weight_mat, labels):
    V = len(labels)
    selected = np.zeros(len(labels))
    no_edge = 0
    selected[0] = True
    MST_connections = []

    while no_edge < V - 1:
        rows_true = np.where(selected)[0]
        columns_false = np.where(np.logical_not(selected))[0]
        """
        based on choose rows with True and columns with False make indexes 
        'ind'  to fetch values from an array 'weight_mat'.
        """
        ind = np.array(np.meshgrid(rows_true, columns_false, indexing='ij')).reshape(2, -1)
        sample = weight_mat[ind[0], ind[1]]
        """
        'i_min' index of the minimum from sample. With the help of which we
         extract the desired index corresponding to the 'weight_mat' array.
        """
        i_min = np.where(sample == np.min(sample[np.nonzero(sample)]))

        x = ind[0][i_min][0]
        y = ind[1][i_min][0]

        MST_connections.append([x, y])
        selected[y] = True

        no_edge += 1

    return MST_connections



def MST_old_prim_new(x, labels):  # pragma: no cover
    G = np.zeros((len(x[0]), len(x[0])))

    for i in range(len(x[0])):

        for j in range(i + 1, len(x[0])):
            weight = np.linalg.norm(x[:, i] - x[:, j])
            G[i][j] = weight
            G[j][i] = weight

    MST_connections = prim_new(G, labels)

    return MST_connections


def gen(n: int) -> list:
    print('Array size at a given iteration', n)
    weight_mat = np.random.uniform(low=-5, high=5, size=(n, n+2))
    labels = np.random.choice([0, 1], n, p=[0.5, 0.5])


    return [weight_mat, labels]


def original(s: list):
    return MST(s[0], s[1])
def new_alg_MSTold(s: list):
    return MST_old_prim_new(s[0].copy(), s[1].copy())


def equality_check(x, y) -> bool:
    """
    Checking for equality of results of two functions: 'original' and 'new_alg'.
    Is there a mismatch in at least one element, if so False.
    """
    tf = np.all(np.round(x, 5) == np.round(y,5))
    print('Comparison result', tf)

    return tf


perfplot.show(
    setup=gen,
    kernels=[original, new_alg_MSTold],
    n_range=[2 ** k for k in range(1, 9)],
    equality_check=equality_check,
    xlabel="len(s)"
)
```

</details>

I also tried an array size of 4096 with numba and below is a graph with the results.

2023-09-10 12:13 UTC, sampan501 requested changes
@quant12345 Thank you for your hard work. Once you add a unit test specific for your changes that verifies that given a mwe, you get the same answer, we should be good to merge

2023-09-10 13:10 UTC, quant12345 commented
> @quant12345 Thank you for your hard work. Once you add a unit test specific for your changes that verifies that given a mwe, you get the same answer, we should be good to merge

@sampan501 This is my second pull request, so I’m not strong in terminology. 
1.mwe is - minimal working examples? 
2.Do I need to write a unit test myself or is this an option that is available in hyppo(maybe I need to activate it somehow)?

2023-09-10 21:45 UTC, closed without merging

2023-09-11 19:04 UTC, sampan501 commented
Yes that test method uses that to estimate a p-value